<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-P0SJP3T6" failures="2" tests="4" name="Test" time="0.375" errors="0" timestamp="7 Jul 2020 09:04:07 GMT">
  <testcase classname="com.testng.rerunfailedtests.RunFailedTestCases1" name="testCase1" time="0.022"/>
  <testcase classname="com.testng.rerunfailedtests.RunFailedTestCases1" name="testCase2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.testng.rerunfailedtests.RunFailedTestCases1.testCase2(RunFailedTestCases1.java:19)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="com.testng.rerunfailedtests.RunFailedTestCases2" name="testCase3" time="0.001"/>
  <testcase classname="com.testng.rerunfailedtests.RunFailedTestCases2" name="testCase4" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.testng.rerunfailedtests.RunFailedTestCases2.testCase4(RunFailedTestCases2.java:19)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 -->
</testsuite> <!-- Test -->
